# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApiClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ApiClient
  pod 'Alamofire', '~> 4.5'	
	pod 'Result', '~> 4.0.0'

  target 'Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
